name: Auto Generate and Commit Missing Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch PR Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching PR changes..."
          gh pr diff --name-only ${{ github.event.pull_request.number }} > changed_files.txt
          echo "Modified files:"
          cat changed_files.txt

      - name: Extract Functions & Generate Tests Using GPT-4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          while IFS= read -r file; do
            if [[ "$file" == *.go ]]; then
              echo "Processing: $file"
              cd "$(dirname "$file")"  # Change to the file's directory

              # Run the extraction script
              MODIFIED_FUNCTIONS=$(go run ../../scripts/extract_functions_gpt.go "$(basename "$file")")
              echo "Modified functions: $MODIFIED_FUNCTIONS"

              for func in $MODIFIED_FUNCTIONS; do
                FUNCTION_CODE=$(awk "/func $func/,/^}/" "$(basename "$file")") # Extract function code
                go run ../../scripts/generate_tests_gpt.go "$func" "$FUNCTION_CODE"
              done

              cd -  # Go back to original directory
            else
              echo "Skipping non-Go file: $file"
            fi
          done < changed_files.txt

      - name: Commit and Push New Tests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No new tests to commit."
          else
            git commit -m "Auto-generated missing tests using GPT-4"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
