name: Auto Generate and Commit Missing Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Fetch PR Changes
        run: |
          CHANGED_FILES=$(gh pr diff --name-only ${{ github.event.pull_request.number }})
          echo "Changed files: $CHANGED_FILES" >> $GITHUB_ENV

      - name: Extract Functions & Generate Tests Using GPT-4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for file in $CHANGED_FILES; do
            MODIFIED_FUNCTIONS=$(go run scripts/extract_functions_gpt.go "$file")
            echo "Modified functions: $MODIFIED_FUNCTIONS"
            for func in $MODIFIED_FUNCTIONS; do
              FUNCTION_CODE=$(awk "/func $func/,/^}/" "$file") # Extract function code
              go run scripts/generate_tests_gpt.go "$func" "$FUNCTION_CODE"
            done
          done

      - name: Commit and Push New Tests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-generated missing tests using GPT-4"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
